spring:
  datasource:
    url: jdbc:mysql://${DEV_DB_HOST}:${DEV_DB_PORT}/${DEV_DB_NAME}
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_ADDRESS}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/auth/google/callback"
            scope:
              - email
              - profile
              - openid
            client-name: Google
            authorization-grant-type: authorization_code

        provider:
            google:
                authorization-uri: https://accounts.google.com/o/oauth2/auth
                token-uri: https://accounts.google.com/o/oauth2/token
                user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
                user-name-attribute: sub
  elasticsearch:
    uris: http://localhost:9200
    username: ${ELASTICSEARCH_USERNAME}
    password: ${ELASTICSEARCH_PASSWORD}
security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expiration-time: ${JWT_EXPIRATION_TIME}
    refresh-expiration-time: ${JWT_REFRESH_EXPIRATION_TIME}
server:
  port: 8081
  shutdown: graceful
management:
  endpoint:
    health:
      group:
        custom:
          include: diskSpace
          show-components: always
          show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    disable-swagger-default-url: true
    operationsSorter: method
    tagsSorter: alpha
  show-actuator: true
paypal:
  clientId: ${PAYPAL_CLIENT_ID}
  clientSecret: ${PAYPAL_CLIENT_SECRET}
  mode: sandbox
bugsnap:
  api:
    key: ${BUGSNAP_API_KEY}



